### ISSUE TITLE
URL default ports

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1328]
It would be nice if we had a word that returned the port or "default port" of a URL.  Something like this:

```factor
CONSTANT: default-ports H{
    { "http" 80 }
    { "https" 443 }
    { "ftp" 20 }
    { "ssh" 22 }
}

: url-port ( url -- port )
   dup port>> [ nip ] [ protocol>> default-ports at ] if* ;
```

Could use a list like this:

https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

(or dynamically use the available one on the OS)

**Comment by bpollack** [comment]
@mrjbq7 This already exists in `io.sockets` as `protocol-port` (which uses `getservbyname`, meaning that any protocol known by the OS will be used). This in turn is used in a word indeed named `url-port`, which seems to have existed in that form since at least 2010 (see 89ae9d96). I think we can close this.

**Comment by mrjbq7** [comment]
That's weird naming coincidence, hah!

On Mac OS X it doesn't seem to work as I expected:

```factor
IN: scratchpad URL" http://google.com" url-port .
f
```

But not because ``protocol-port`` fails:

```factor
IN: scratchpad "http" protocol-port .
80
```

It's because it seems to return ``f`` when ``port`` is ``f``, and also when ``port`` is same as the default... 

```factor
IN: scratchpad URL" http://google.com:80" url-port .
f

IN: scratchpad URL" http://google.com:800" url-port .
800

```
Anyway, the ``protocol-port`` is what I wanted, so I'm closing this bug.
