### ISSUE TITLE
Buggy file-readable on Windows?

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1470]
From the mailing list:

https://www.mail-archive.com/factor-talk@lists.sourceforge.net/msg07337.html

>  I've got another question about the file-readable? word. The documentation says that it "returns whether the file specified by path is readable by the current process." Here's my experiment:
>
>  "C:\\boot.ini" file-readable? .
> -> t
>  "C:\\boot.ini" sha-256 checksum-file hex-string .
> -> Exception "Access is denied."
>
>  Being a non-root user in Windows, I have no permission to read C:\boot.ini, but file-readable? returns true.

**Comment by AlexIljin** [comment]
file-readable? checks if it can create the file-info tuple and returns true on success. And indeed, the metadata about boot.ini in the tuple is correct. But that doesn't mean that the file contents can be accessed by the current user. It seems like either the documentation is incorrect, or the implementation needs to be updated.
Tested on WinXP SP3, NTFS, under non-admin user account.

**Comment by erg** [comment]
First of all, ``"C:\boot.ini" file-readable? .`` is escaping the ``b`` as a backspace.

It should be:  ``"C:\\boot.ini" file-readable? .`` or ``"C:/boot.ini" file-readable? .``

Next, ``boot.ini`` is not present on Windows 10, only pre-Windows 7.

We could check the ``attributes>>`` slot of the ``file-info`` instead of if it allows ``file-info`` or not. Even then, ``dir /a:h c:`` shows ``pagefile.sys`` and ``swapfile.sys`` but I can't checksum them because roughly "another program has opened these files".

**Comment by erg** [comment]
Should we try to actually open the file and read a byte instead?

The R property shown by ``attrib`` is all but useless.
```
c:\>attrib
A            C:\ANG0
A  SHR       C:\bootmgr
A  SH        C:\BOOTNXT
A  SHR       C:\BOOTSECT.BAK
A            C:\cmd.zip
A  SH        C:\pagefile.sys
A  SH        C:\swapfile.sys
```

**Comment by AlexIljin** [comment]
R means read-only, which is a file attribute, not a permission statement. The attribute is a soft deterrent to prevent accidental file modification.

To check the read permission one has to use try to CreateFile with GENERIC_READ access. At that point OS will check all the applicable permissions of the current process/user and return either the valid file handle on success, or the INVALID_HANDLE value (or whatever it's called) on failure. The reasons for failure can be many (no such file exists, no permission, etc.), but the point is that for whatever reason we can't read the file.

There is no need to actually try to read a byte, the simple handle check is enough. In fact, reading from the file could have performance penalty if the file is on a CD/DVD drive, network share, etc. All kinds of caches will have to be allocated and so on.

**Comment by AlexIljin** [comment]
I noticed that Factor requests the BACKUP_SEMANTICS flag on opening files, presumably to be able to open more files and to fail less often (or so that one can write file backup software in it). In any case, when checking if a file is readable one should use the same flags to avoid mismatch. It would be weird if file-readable? returns f, but trying to actually read the file succeeds.

**Comment by AlexIljin** [comment]
Wow, did I just fix something?

**Comment by erg** [comment]
Fixt!
