### ISSUE TITLE
On Windows, slides vocab displays illegible text

### ISSUE THREAD

**Issue by slavapestov** [factor/factor#152]
This is because Uniscribe doesn't support rendering to a context with an alpha channel. Find a workaround.

**Comment by mrjbq7** [comment]
@erg I think this is not too hard to do, can you send me login to windows VM?

**Comment by mrjbq7** [comment]
oh wait you sent me a link already lemme get that

**Comment by jonenst** [comment]
In the meantime, like b81a5f9c7a13f11119dfbf53a5574201b35510be:
```diff
diff --git a/extra/slides/slides.factor b/extra/slides/slides.factor
index 8e90d91..d077d28 100644
--- a/extra/slides/slides.factor
+++ b/extra/slides/slides.factor
@@ -3,7 +3,7 @@
 USING: accessors arrays colors fry help.markup help.stylesheet
 io.styles kernel math math.ranges models namespaces parser
 sequences ui ui.gadgets ui.gadgets.books ui.gadgets.panes
-ui.gestures ui.pens.gradient ;
+ui.gestures ui.pens.gradient ui.pens.solid system ;
 IN: slides

 CONSTANT: stylesheet
@@ -53,23 +53,32 @@ CONSTANT: stylesheet
         } format
     ] ($block) ;

+: divider-interior ( -- interior )
+    os windows = [
+        T{ rgba f 0.25 0.25 0.25 1.0 } <solid>
+    ] [ {
+            T{ rgba f 0.25 0.25 0.25 1.0 }
+            T{ rgba f 1.0 1.0 1.0 0.0 }
+        } <gradient>
+    ] if ;
+
 : $divider ( -- )
     [
         <gadget>
-            {
-                T{ rgba f 0.25 0.25 0.25 1.0 }
-                T{ rgba f 1.0 1.0 1.0 0.0 }
-            } <gradient> >>interior
+            divider-interior >>interior
             { 800 10 } >>dim
             { 1 0 } >>orientation
         gadget.
     ] ($block) ;

 : page-theme ( gadget -- gadget )
-    {
-        T{ rgba f 0.8 0.8 1.0 1.0 }
-        T{ rgba f 0.8 1.0 1.0 1.0 }
-    } <gradient> >>interior ;
+    os windows = [
+        T{ rgba f 0.8 0.8 1.0 1.0 } <solid>
+    ] [ {
+            T{ rgba f 0.8 0.8 1.0 1.0 }
+            T{ rgba f 0.8 1.0 1.0 1.0 }
+        } <gradient>
+    ] if >>interior ;

 : <page> ( list -- gadget )
     [
```

**Comment by mrjbq7** [comment]
@jonenst good idea! patch in 9d428cbcaf22e3f7bb65c20815dd97a4d2af9e40

**Comment by nicolas-p** [comment]
The first link above says:

> If you want to draw text without a background fill, SetBkMode(hdc,TRANSPARENT) will tell GDI to leave the background when drawing text.

So I added the word `SetBkMode` in `windows.gdi32` and then tried to use it in `draw-string` (if I remember well). But when I type this: 
```factor
"thing" <label> transparent <solid> >>interior gadget.
```
I still get a black rectangle. Has anyone tried something similar before?

**Comment by mrjbq7** [comment]
I tried it and it has to do with how ``windows.uniscribe`` does the compositing, basically always rendering a background color.

**Comment by mrjbq7** [comment]
We need to make premultiplied alpha bitmaps and I got close to getting this working then got distracted.  I'll try and work on it a bit later.

**Comment by catb0t** [comment]
@mrjbq7  did you get anywhere with your work on premultiplied alpha bitmaps?

**Comment by mrjbq7** [comment]
Didn't ever get it quite to work, then got distracted by other things.  So not finished yet.

**Comment by AlexIljin** [comment]
Using GDI+ instead of GDI seems to be a bad idea, as [explained here.](https://theartofdev.com/2013/08/12/the-wonders-of-text-rendering-and-gdi/) The main reason is, GDI is up to date, and GDI+ is stale. Also, GDI+ is about ten times slower than GDI.

I don't know what "premultiplied alpha bitmaps" are, so I did a separate research on drawing text with transparency, and [this post](https://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=21677&start=15#p93759) explained it to me.

The algorithm is as follows:
1. render black text on white background into a bitmap with alpha channel, antialiasing will create some gray pixels;
2. copy any color channel into the transparency channel. For example, take all Green pixel values [0..255] and copy them into the alpha values;
3. fill the image completely with the desired text color X.

The resulting image will be a rectangle of color X with the transparency layer in the shape of the rendered text. The text pixels that were black on step 1 will have 0 transparency, so the image filled with color X will display color X at these points. The pixels that were white on step 1 will have transparency = 255, so the background will be fully transparent. The gray pixels will have intermediate transparency level [1..254], and the color X will be that much transparent, ready to blend in with any destination background.

**Comment by AlexIljin** [comment]
I think I may have mixed up the transparency values. In the previous comment I assumed that alpha = 255 is fully transparent, and alpha = 0 is fully opaque. If it's actually the other way around, then on step 1 we need to render white text on black background (instead of black on white), and the rest of the recipe stays the same.

**Comment by AlexIljin** [comment]
Confirmed: it should be white text on black background.

**Comment by erg** [comment]
Finally fixed 🎆
