### ISSUE TITLE
32 bit old hardware bootstrap error

### ISSUE THREAD

**Issue by jonenst** [factor/factor#1582]
Bootstrapping on this old pc fails at the begining with the following error:
```
Loading resource:basis/locals/definitions/definitions.factor
Loading resource:basis/see/see.factor
Loading resource:basis/locals/prettyprint/prettyprint.factor
Loading vocab:bootstrap/bootstrap-error.factor
Loading resource:basis/debugger/debugger.factor
You have triggered a bug in Factor. Please report.
critical_error: The die word was called by the library.: 0
```

Downloading the dev release works:
```
Factor 0.98 x86.32 (1741, heads/master-0d2859124e, Mon Mar 21 21:07:24 2016)
[GCC 4.8.4] on linux
```

The pc is a core2duo running lubuntu 14.04:
```
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 Duo CPU     L7500  @ 1.60GHz
```

Bootstrap logs : http://pastebin.com/EBVLZsCt

**Comment by mrjbq7** [comment]
Is that with the kernel error patches today or a problem that's been there for awhile?

**Comment by mrjbq7** [comment]
(I had a similar big today hadn't updated properly)

**Comment by bjourne** [comment]
Yes, it's because of my committ earlier today. :p The tb is in the `T{ continuations:condition T{ source-files.errors:source-file-error T{ lexer:lexer-error 1 39 "USING: continuations kernel io debugger vocabs words system namespaces ;" T{ vectors:vector { T{ lexer:lexer-parsing-word syntax:USING: 1 "USING: continuations kernel io debugger vocabs words system namespaces ;" 6 } 0 } 1 } T{ continuations:condition T{ source-files.errors:source-file-error T{ lexer:lexer-error 154 39 "            [ first-unsafe KERNEL-ERROR = ]" T{ vectors:vector { T{....` block of text.

**Comment by erg** [comment]
Seems fixed. Reopen if that's not the case.
