### ISSUE TITLE
SSL all the things

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1596]
planet.factorcode.org

gitweb.factorcode.org

*.factorcode.org

**Comment by erg** [comment]
Wildcards don't work. grr letsencrypt.

www.factorcode.org, www.concatenative.org, factorcode.org, concatenative.org, paste.factorcode.org, docs.factorcode.org, gitweb.factorcode.org, planet.factorcode.org, builds.factorcode.org, irclogs.factorcode.org

**Comment by erg** [comment]
Done

**Comment by jonenst** [comment]
www.factorcode.org uses an invalid security certificate. The certificate expired on 08/07/2016 09:05 AM. The current time is 08/16/2016 05:10 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Also, can you add  https://downloads.factorcode.org (and update build.sh) so that we don't get p0wned when we download new images :) ?
