### ISSUE TITLE
Remove the HEX{ syntax?

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1695]
The `HEX{`  syntax is a method to create byte-array literals from hexadecimal numbers. It doesn't seem to be very useful, imho. E.g `HEX{ C0 80 80 00 }` is exactly the same as `B{ 0xc0 0x80 0x80 0x00 }` but six characters shorter to type.

**Comment by mrjbq7** [comment]
I generally agree, but I think it allows grouping bytes together instead of each single byte value specified. Also I kind of think we should let 1000 syntaxes bloom. But it is a little redundant and also `HEX{` doesn't look enough like `B{` and it creates a byte array.

**Comment by jonenst** [comment]
I think it's from before the 0x hex syntax for numbers in math.parser. when
there was only the HEX:  parsing word. So i guess HEX{ existed because B{
HEX: de HEX: ad HEX: be HEX: ef } was a pain to write. B{ 0xde 0xad 0xbe
0xef } is more manageable..

Le 20 août 2016 02:58, "John Benediktsson" <notifications@github.com> a
écrit :

**Comment by mrjbq7** [comment]
So we don't use ``HEX{`` much (mostly in tests).  I'm +1 on deleting it, I think.

**Comment by mrjbq7** [comment]
Even though it is cool to do this:

```
HEX{ FFFE0000 31000000 32000000 33000000 }
```

**Comment by mrjbq7** [comment]
Fixed in 19447e44a497f3a278b79a73d22a5c7e72f16654.

**Comment by bjourne** [comment]
:+1:
