### ISSUE TITLE
"No suitable arithmetic method" in text-based listeners but not in GUI Listener

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1706]
I'm not sure this is a bug, but I'm pretty sure I didn't do anything wrong and I'm not sure what causes this, so I'll ask here.

If I have that same file from #1705, config.json, and I run some stream-y code to print its contents...

```
"config.json" utf8 [ input-stream get stream-lines print ] with-file-reader
```

In the GUI Listener, the files' contents are printed, like I expected.
![guiok](https://cloud.githubusercontent.com/assets/3238748/18296478/f85b795e-7477-11e6-8d6b-5f05506fe767.png)

But in either `listener` (textual) or `readline-listener`:
![noguinook](https://cloud.githubusercontent.com/assets/3238748/18296550/6f174ed8-7478-11e6-8058-05d05a1a63e1.png)

The error in the second image is the same for any text file: comparing the first line of the file with `127` using `<=`. I'm not sure why such an error is thrown -- the code seems like it should be correct, but why is the behaviour different? Is that a bug  or a feature?

**Comment by mrjbq7** [comment]
Well, you can't ``print`` the result of ``lines`` because that's an array of strings, not a string, and print only takes strings.

As for why it works in the UI listener, that's weird and maybe it shouldn't but see this simplified test case:

```
IN: scratchpad { "hello" "world" } print
hello
world
```

Also, you don't have to do ``input-stream get stream-lines``, you can just call ``lines``.

**Comment by mrjbq7** [comment]
P.S., in the console listener, you can call ``:help`` to see information about the error, and if you type ``:c``, you can get the call stack which shows you that ``print`` is calling ``M\ object encode-string-utf8``, which calls ``<=`` which throws ``no-math-method``.  It's not quite as easy as click around in the error dialog in the UI, but gets you similar information (using ``:r`` and ``:s`` also).

**Comment by jonenst** [comment]
it works (weirdly) in the UI listener because ui.gadgets.label:
> Class description
A label displays a piece of text, either a single line string or an array of line strings.

But it's really half working:
```factor
IN: scratchpad { "foo" "bar" } print
foo
bar
IN: scratchpad { "foo" "bar" } [ print ] each
foo
bar
```
In the first case, you can't select the lines separately...

Also we call document.private:split-lines on the input, which happen to not throw an exception for now by chance for an array of strings, but really assumes that the input is a string. 

I think the following patch improves the situation:
```diff
diff --git a/core/io/io.factor b/core/io/io.factor
index fc804f0..8082650 100644
--- a/core/io/io.factor
+++ b/core/io/io.factor
@@ -31,7 +31,8 @@ GENERIC: stream-seekable? ( stream -- ? )
 GENERIC: stream-length ( stream -- n/f )
 
 : stream-print ( str stream -- )
-    [ stream-write ] [ stream-nl ] bi ; inline
+    [ "" like ] dip
+    [ stream-write  ] [ stream-nl ] bi ; inline
 
 ! Default streams
 MIXIN: input-stream
```

**Comment by mrjbq7** [comment]
Yeah, maybe we shouldn't allow writing arrays of strings to the UI listener...
