### ISSUE TITLE
High overhead when launching processes (compared to Python)

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1749]
E.g
```factor
IN: scratchpad [ { "echo" "hi" } utf8 [ contents ] with-process-reader ] time
Running time: 0.109429914 seconds
```
In Python:
```python
import subprocess, time ; start = time.time() ; subprocess.check_output(['echo', 'hi']) ; print (time.time() - start)
0.00732207298279
```
So 109ms overhead in Factor and only 7ms in Python.

**Comment by mrjbq7** [comment]
The problem is that we have a ``waitpid`` thread in the parent process that loops every 100 milliseconds.  I changed it to start with 5 milliseconds, then back-off linearly an additional 5 milliseconds each time until 100 milliseconds.  That might be too short?  Maybe 10 is better to avoid the first few being unnecessary, dunno.

But it mostly fixes the latency problem.

On my machine:

```factor
IN: scratchpad [ { "echo" "hi" } utf8 [ contents ] with-process-reader ] time
Running time: 0.027609682 seconds
```

vs. Python:

```python
>>> import subprocess, time ; start = time.time() ; subprocess.check_output(['echo', 'hi']) ; print (time.time() - start)
'hi\n'
0.00584697723389
```

Better would be an inter-process notification of some sort when the child finishes, probably.

@bjourne?

**Comment by mrjbq7** [comment]
Some other ideas:

* Spawn a Factor thread for each process, and call ``waitpid`` without ``WNOHANG`` and then have another thread that sleeps until the closest process timeout to interrupt.

* Implement ``SIGCHLD`` and detect the child process exiting, also have another thread for process timeout.

**Comment by mrjbq7** [comment]
Actually, I have some better ideas about this I will try and look into later today or tomorrow.

**Comment by bjourne** [comment]
Reducing the polling timeout. If we can get the overhead down from 100ms to 5ms that's good enough for me.
