### ISSUE TITLE
Why a critical_error on bootstrap when present is defined on array objects?

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1834]
If you apply this diff to master (basically adding a working, test-passing `present` method for `array` objects):
```
diff --git a/basis/present/present.factor b/basis/present/present.factor
index eae0f43021..ec03395e71 100644
--- a/basis/present/present.factor
+++ b/basis/present/present.factor
@@ -27,3 +27,22 @@ M: effect present effect>string ;
 M: f present drop "" ;
 
 M: pathname present string>> ;
+
+M: array present
+    dup empty?
+    [ drop "{ }" ]
+    [
+        [
+            [ {
+                  { [ dup string? ] [ "\"" dup surround ] }
+                  { [ dup f = ]     [ drop "f" ] }
+                    [ ] ! otherwise just present it
+              } cond present
+            ] map
+        ]
+        [ length ]
+        bi
+        [ "%s " ] replicate "" join
+        vsprintf "{ " "}" surround
+    ]
+    if ;
```
`./build.sh update` fails with the following error:

```
Loading resource:basis/present/present.factor
Loading vocab:bootstrap/bootstrap-error.factor
Loading resource:basis/debugger/debugger.factor
Loading resource:basis/io/styles/styles.factor
Loading resource:basis/present/present.factor
You have triggered a bug in Factor. Please report.
critical_error: The die word was called by the library.: 0
Starting low level debugger...
```

I was going to make a pull request to add [some of my downstream, generally-useful `present` methods](https://github.com/catb0t/exercism.factor/blob/master/exercism/autogen-exercises/autogen-exercises.factor#L36) to upstream but apparently Factor finds this fundamentally unacceptable. 

Interestingly, if you build Factor with the normal `present` vocab, and then apply this diff, the VM starts and runs perfectly fine, and you can `{ 1 2 } present` all day. 

Can anyone explain why this is? I'm not really sure how to dig in and figure this out myself, but it's certainly unexpected.

**Comment by mrjbq7** [comment]
Hi @catb0t that can't be the full patch because it is missing a ``USING:`` for ``formatting`` which would cause a different error in bootstrap.  I will need to look into it, but I suspect that you will run into mutually dependent issues where ``formatting`` depends on ``present`` but then ``present`` depends on ``formatting`` which would error without some effort to make it bootstrap using ``DEFER:`` or a separate vocabulary that captures the common dependencies.

Your error is most likely the ``USING:`` and then when it tries to trigger a bootstrap error it runs into a problem where ``io.styles`` which is needed by the ``debugger`` tries to load ``present`` but can't because it already loaded with an error.  That shouldn't be a ``critical_error`` but I guess it is.

As an aside, why are you using ``present`` in this way? It's not meant to do general purpose formatting like the ``formatting`` vocab.   Also, it's curious you're using ``%s`` instead of just ``present`` recursively?  Kind of mixed.

As another aside, we could try and improve the "format sequences" directive in ``printf`` so you get the result you want with just:

```"%[%s, %]" printf``

**Comment by mrjbq7** [comment]
Also I think your method is better implemented without ``formatting`` and simpler as this:

```factor
M: array present
    [ "{ }" ] [
        [
            [ dup string? [ "\"" dup surround ] [ present ] if ] [ "f" ] if*
        ] map " " join "{ " " }" surround
    ] if-empty ;
```

**Comment by mrjbq7** [comment]
Oh, and I took a look at your downstream methods and I think you'd generally be better of using ``unparse`` in the ``prettyprint`` vocabulary to print your stuff because you seem to be using ``present`` to generate a "Factor-like" representation of your objects...  which is what ``unparse`` is for.  Allowing you to typically print your objects in a way that they could be pasted back in to recreate the original object.

**Comment by catb0t** [comment]
Oh, that was kind of silly then, sorry. Thanks for all your help and time though!

**Comment by mrjbq7** [comment]
Not silly at all!
