### ISSUE TITLE
openssl 1.1.0: ca md too weak

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1843]
In the new openssl version, the server certificate we are using for testing is not accepted. 
```factor
<secure-config> "vocab:openssl/test/server.pem" 
>>key-file "vocab:openssl/test/dh1024.pem" >>dh-file 
<secure-context>
error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak
```
It appears that it is the `vocab:openssl/test/server.pem` file that openssl doesn't like.

**Comment by catb0t** [comment]
https://bugs.archlinux.org/task/53831

> OpenSSL 1.1 bails out on CA certificates with MD5 ciphers.
> Searching for the error message, there seems to be a workaround by setting @SECLEVEL=0 in the allowed cipher list

https://github.com/sabnzbd/sabnzbd/issues/811

> It sounds like the cert generated was just done on old openssl/awhile ago.
> I would ask for the cert so we can validate... Or they can just move that cert out and try generating a new one and see.if it's all good now.

seems like if the `.pem` file can be regenerated by OpenSSL 1.1 to work with 1.0 as well then it might fix it?

**Comment by bjourne** [comment]
How would you regenerate the cert?

**Comment by catb0t** [comment]
I know basically nothing about OpenSSL or certificate technology. I also don't have OpenSSL 1.1.0 installed because it's not in Ubuntu's repos and I can't be bothered to build it from source.

https://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl

> You can do that in one command:
> ```
> openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
> ```

If `openssl version` shows `OpenSSL 1.1 [...]` for you then I'd imagine this command will do the trick, maybe?

**Comment by bjourne** [comment]
Your command to generate a new cert seem to have worked!
