### ISSUE TITLE
Linux fullscreen mode is broken for game-worlds

### ISSUE THREAD

**Issue by erg** [factor/factor#1879]
Entering fullscreen changes the size but the drawing only happens in the top left and the rest of the window is white.

```factor
"terrain" run
! hit alt-enter
```

**Comment by mrjbq7** [comment]
That seems like a bug with terrain demo, not full screen mode since it works with the Listener.

**Comment by erg** [comment]
It might have to do with 4k resolution. I'm not sure if we fixed that on Linux. (It works for the Listener but maybe not for opengl in general)

**Comment by mrjbq7** [comment]
I don't think we set ``gl-scale-factor`` on anything besides macOS.

Also, it's a global setting so it doesn't work for macs that have both non-retina and retina screens.

Also, it's only currently set to 2.0 so it doesn't work on non-4k screens I would guess.

**Comment by jonenst** [comment]
It's a regression from my fix to the "lagging" effect of window resize on linux : #1487 .
reverting 14f51e2dd53 fixes the fullscreen mode on game worlds.
I'll look into it.

**Comment by jonenst** [comment]
This reproduces the problem :
```factor
 : 20msbusy ( -- ) nano-count 20000000 + [ nano-count > ] curry loop ;
 [ 20msbusy ] 10 milliseconds  every ! factor will run at 100% cpu but will still accept input in the listener
! try resizing, it doesn't work
stop-timer ! stop the timer, now it works.
```

The following fixes the problem, and I think it's the proper fix:
```diff
diff --git a/basis/ui/backend/gtk/gtk.factor b/basis/ui/backend/gtk/gtk.factor
index 31e4aac..f9c38c1 100644
--- a/basis/ui/backend/gtk/gtk.factor
+++ b/basis/ui/backend/gtk/gtk.factor
@@ -77,6 +77,7 @@ M: gtk-clipboard set-clipboard-contents
 :: with-timer ( quot -- )
     <timer-funcs> &free
     GSource heap-size g_source_new &g_source_unref :> source
+    source G_PRIORITY_DEFAULT_IDLE g_source_set_priority
     source f g_source_attach drop
     [ quot call( -- ) ]
     [ source g_source_destroy ] [ ] cleanup ;
```

So here's what I understand from this and #1487 :
Before 1487, we were using the configure event on the window for drag + resize. This event was fired all the time. After 1487, we were using the configure event of the window (for drag) and the configure event of a single child widget of the window (for resize).
What we have in this issue is that when factor is "busy", the configure event on the child widget is never fired. I couldn't find the docs saying that these event have different priority, but that's what it look like.

In gdk, if there is always an event with a higher priority that is ready, lower priority events will never fire.

Factor creates gdk events with default priority when one of the cooperative threads is ready (that's what the timer GSource in basis/ui/backend/gtk.factor does)

On https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#G-PRIORITY-HIGH-IDLE:CAPS we see :
> GTK+ uses G_PRIORITY_HIGH_IDLE + 10 for resizing operations, and G_PRIORITY_HIGH_IDLE + 20 for redrawing operations. (This is done to ensure that any pending resizes are processed before any pending redraws, so that widgets are not redrawn twice unnecessarily.)

So I think that the configure event on the window has a default priority, but the configure event on the child has G_PRIORITY_HIGH_IDLE + 10

So we use the next lower priority G_PRIORITY_IDLE to allow the events from gdk to be fired.
What do you think ?

**Comment by bjourne** [comment]
That looks like a reasonable way to do it. We also really should try and upgrade the gtk backend to gtk3 soon.

**Comment by mrjbq7** [comment]
Are you going to apply this patch @bjourne ?

**Comment by bjourne** [comment]
Will do! Btw, it is strange how much different Factor works in Ubuntu Unity compared to KDE5. I run the latter and everything works flawlessly, but in Unity there's like quirks all over. Like resize is superfast is kde but sluggish in unity and so on.
