### ISSUE TITLE
clean images don't upload, detached current branch reports HEAD when it could do better

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1904]
I have noticed that we have a lot of images in: http://downloads.factorcode.org/images/ It is easy to mess up by selecting the wrong one. Perhaps some of them aren't used and can be removed?

**Comment by jonenst** [comment]
Watch out, the build directory is super useful for bisecting, don't delete
it. Unless there is some other method I don't know..

Le 16 janv. 2018 20:26, "Björn Lindqvist" <notifications@github.com> a
écrit :

**Comment by erg** [comment]
You're meant to use build.sh and it grabs the right one, so besides a few stray boot images that I can delete, I think it's good to have many boot images!

We started archiving based on git-id and lately by branch because losing the boot image means it's very hard to bootstrap an older version. Also, like @jonenst mentioned, bisecting is actually possible -- use the boot image with the checksum closest backwards in git history to the git-id you're on (since boot images only change when core/ changes).

**Comment by bjourne** [comment]
Right, don't delete that one! But like what is the difference between the HEAD, master, latest and clean directories?

**Comment by erg** [comment]
HEAD should go away, this patch fixes our reporting ``master`` as ``HEAD`` in a detached head git state:
```
IN: cli.git
: git-current-branch ( -- name )                                                                                                                 
     ! { "git" "rev-parse" "--abbrev-ref" "HEAD" }
     { "git" "name-rev" "--name-only" "HEAD" }
     utf8 <process-reader> stream-contents
     [ blank? ] trim-tail ;
```

- master - good
- clean - good, should be the gitid of the last uploaded binary
- HEAD - bad, should be deleted
- latest - bad, should be deleted

**Comment by mrjbq7** [comment]
@erg is there something still to do here?

**Comment by erg** [comment]
Clean images are uploading.

Closing!
