### ISSUE TITLE
critical_error: Bad GC op: 2

### ISSUE THREAD

**Issue by wrl** [factor/factor#1982]
Ran across this while hacking earlier.

![factor_welp](https://user-images.githubusercontent.com/1824/37692008-3c83eb8c-2cb6-11e8-9ddb-7f65ae3b6d7d.png)

While reproducing, I also got Factor to crash with a bus error and report
`fatal_error: Memory protection fault during gc: 0x18`

Using 0.97 on Arch Linux.

**Comment by AlexIljin** [comment]
The sample code seen in the Listener produces the "Data stack underflow" error, because `with` requires two operands, while there is only one array present on the stack. It seems to me that the GC error is either triggered by some earlier work in the session, or we have something wrong with exception throwing or catching on Arch.

**Comment by mrjbq7** [comment]
If you can reproduce it again, can you post the last few lines of the results of ``.s``, ``.r``, and ``.c``?

**Comment by erg** [comment]
I recommend the nightly builds instead of .97 as the tree has diverged so much since then. If there's a reproducible bug on .97 that would be useful, but .97 is likely to have some gc bugs that have been fixed.

Please reopen if you can get a test case that crashes on .97 or nightly. 🍨

**Comment by catb0t** [comment]
I can't reproduce this on Linux 0.97. You really ought to use a newer, nightly version of Factor, since so many features have been added :)
