### ISSUE TITLE
recaptcha v1 is shutdown

### ISSUE THREAD

**Issue by jonenst** [factor/factor#1991]
http://paste.factorcode.org:8080/new-paste

![image](https://user-images.githubusercontent.com/89208/39185300-0342959a-47c7-11e8-92e6-9de29a5e8801.png)

**Comment by catb0t** [comment]
https://developers.google.com/recaptcha/docs/faq#what-happens-to-recaptcha-v1

**Comment by bpollack** [comment]
The fact chloe is XML-based, not HTML5-based, is starting to really hurt us; the right script tag for v2 or v3  reCAPTCHA is `<script .... async defer>`, which isn't valid XHTML5, so we have to do `<script ... async="async" defer="defer">`, which unsurprisingly doesn't work properly. (This isn't a show-stopper, but means that a chloe-based reCAPTCHA v2 is going to block rendering until the script loads.)

I'm going to try to fix this up anyway, but I think we need n HTML5-based chloe-2 or something sooner rather than later if we're serious about Furnace.

**Comment by catb0t** [comment]
#1899 a modern HTML5 parser is defnitely something we should be looking toward

**Comment by bpollack** [comment]
A _parser_ is entirely separate from a _generator_. I'm only talking about the first here; a cleaner version of fhtml would be fine for the latter.

**Comment by bpollack** [comment]
Resolved in 84d480700c59e4110e768b9847db6c8ff8ff016d
