### ISSUE TITLE
Too many obsolete branches on GitHub

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#2017]
Hello!

  I've recently fetched from GitHub after a while of not tracking the Factor repo closely.
  I saw the `nipd` branch with one commit in it, so I decided to give it a try and cherry-picked the commit into master, only to find out that it was already included. So, the branch is simply not needed, but anyone fetching from GitHub would get it.
  Could you, guys, purge the branches that are no longer needed from the repo?

**Comment by erg** [comment]
What’s the problem with having branches? The nipd branch got merged basically. I was using it to test travisci with PRs.

Likewise, the clean branches are for testing with travis and to know the last time we got a clean build.

I just recently made factorcode push all branches to github every five minutes instead of just pushing master.

I would prefer to keep as many branches as anyone wants and close this issue unless there is some compelling reason to delete branches. (They share most of the .git objects anyway)

**Comment by AlexIljin** [comment]
@erg: I would prefer to keep as many branches as anyone wants
No objection from me here, but a question does anyone want the `nipd` branch? If so, for what purpose? The only commit it contains conflicts with the latest `master` because of syntax errors (it won't even compile), what's the use of that? It's just noise, IMO.

**Comment by erg** [comment]
I deleted a couple of branches. The rest need more consideration.

**Comment by AlexIljin** [comment]
Thank you!

**Comment by catb0t** [comment]
Well, I will say I have thought before that they should be pruned, because it becomes quite a  task to figure out the point and meaning of each different branch -- especially after they have 100s of new commits and can't be easily compared.

If only to improve usability the "redundant" (to me) old branches like `modern-harvey` (superseded by `modern-harvey2`?), `char-rename`, or `db4` could be cut away  or stored elsewhere  -- again, just to minimise confusion about dev branches.

**Comment by mrjbq7** [comment]
Agreed, in general.

Specific depends on the branch and desire to cleanup.
