### ISSUE TITLE
List literals request

### ISSUE THREAD

**Issue by h0le** [factor/factor#2019]
It would be convenient to have literals for linked lists (from `lists` vocabulary). Something like `L{ 1 2 3 }`.

**Comment by erg** [comment]
Wait for it...!

**Comment by v0idNULL** [comment]
@erg What?

**Comment by v0idNULL** [comment]
@erg I think it is need to mention about list literals in documentation.

**Comment by erg** [comment]
Docs are a good idea but my plan for the parser is to make a ``GENERIC: sequence>object ( seq -- obj )`` word and change it to ``list{ 1 2 3 }`` and it's pretty much self-documenting. I'll add some docs until then.

**Comment by v0idNULL** [comment]
@erg Is there something like change log for Factor development process?

**Comment by mrjbq7** [comment]
Aside from following the commits we don’t have a summarized change log until we make one for the new release. We are close to finalizing 0.98 release.

**Comment by erg** [comment]
I had to revert this because I noticed a regression.

Lazy lists are forced by the listener, which is bad. We need to also give a literal syntax for lazy lists like ``LL{ }`` or ``lazy-list{ }``.

**Comment by v0idNULL** [comment]
I think, lists must be lazy by default. And interactive in Listener.
Maybe we need to keep `L{ ... }` literal for (lazy) lists. Listener obviously must not force list and shows it like `L{ 1 _ }`. Where `_` (or other) is some clickable dumb symbol for tail (cdr). After clicking on it, Listener calculate next member (if exists) and shows `L{ 1 2 _ }`.
For entire list we have `L{ 1 2 3 }`, what equals to `L{ 1 2 3 L{ } }` and `L{ 1 L{ 2 L{ 3 L{ } } } }`.
Does this have sense? Is it implementable?

**Comment by mrjbq7** [comment]
That's a fun idea.

Yes, totally implementable.

Maybe through an ellipsis placeholder you can click on to get the next list
(so maybe after clicking the ... in L{ 1 ... } you get L{ 2 ... }).  Not
sure if the "click to expand in-place" is that easily implementable, but
perhaps.

**Comment by jonenst** [comment]
I don't see the problem of evaluating finite lazy lists of literal values. So the question should be what would the syntax for non trivial lazy lists ? Something like this ?
```LL{ [ http-get-foo ] [ readline-user ] [ ackerman-8-8 ] }```
which would progressively turn into
```LL{ "<doctype html>..." [ readline-user ] [ ackerman-8-8 ] }```

What about infinite lazy list literals ? I'm not sure we need them.

**Comment by spacefrogg** [comment]
> What about infinite lazy list literals ? I'm not sure we need them.

Literal lazy lists are can only be infinite if they contain at least one loop, which is easily detectable, and pretty printing could be solved by a syntactic construct like in Common Lisp, which marks the entry and exit points of the loop like this: `#1=(1 2 3 . #1#)`. This is actual code, that can be read again by the evaluator, not only a "semantic" representation. (But lists are not lazy in CL.)

Also, the CL example shows the most complex form of a literal list, especially because it explicitly shows the content of the cdr (after the dot). A literal list notation in factor should maybe also allow to explicitly specify the content of the last cdr to not be a list. Maybe as, `L{ 1 2 _ 3}`?

Cycles could be represented like this: `L{ _: 1 1 2 3 _ _: 1 }`, where the first `L{ _: 1` corresponds to `#1=(` from the CL example and the next `_: 1` to `#1#`. So, the discrimination happens, because the first `_:` directly follows the opening brace of the list. The number argument is necessary for the same reason as in CL, there may be multiple cycles in a list.

**Comment by jonenst** [comment]
> What about infinite lazy list literals ? I'm not sure we need them.

I was thinking of haskell's literal lazy lists : https://en.wikibooks.org/wiki/Haskell/Lists_II#Infinite_Lists . Cycling lists are also useful.

**Comment by spacefrogg** [comment]
Sure, but Haskell's `[x..]` is not a literal list, although it looks like it. It's a function that generates a list.

**Comment by mrjbq7** [comment]
Pushed a change to only print ``car`` and make ``cdr`` display ``~more~`` when there are more items.   This will calculate the first element in the list if it's lazy for display purposes.

4b45df48f8543509e6776aabe3d80e59443d7042

**Comment by mrjbq7** [comment]
Alternatively, we could use the ``L{`` syntax only for ``cons-state`` objects, and print all the other lazy list types as their tuple syntax... for now I'll do that maybe.

**Comment by kusumotonorio** [comment]
I wasn't aware of the discussion of this place, so I recently implemented a list literal notation syntax of my own.

If you want to determine the literal notation syntax of that factor standard, it would be nice to have a dot notation equivalent.

**Comment by kusumotonorio** [comment]
My current implementation looks like this:
```
IN: scratchpad L{ 1 L{ 2 3 } } 

--- Data stack:
L{ 1 ~cons-state~ }
IN: scratchpad dup .
L{ 1 L{ 2 3 } }

--- Data stack:
L{ 1 ~cons-state~ }
IN: scratchpad L{ 1 L{ 2 3 } || L{ } }

--- Data stack:
L{ 1 ~cons-state~ }
L{ 1 ~cons-state~ }
IN: scratchpad =

--- Data stack:
t
```
Unfortunately, my implementation has a bug that causes the following to not display correctly:
```
IN: scratchpad L{ L{ 1 2 } || L{ 2 3 } }

--- Data stack:
L{ ~cons-state~ 2 3 }
IN: scratchpad dup .
L{ L{ 1 2 } 2 3 }

--- Data stack:
L{ ~cons-state~ 2 3 }
IN: scratchpad inspect
cons-state
0 car L{ 1 2 }
1 cdr L{ 2 3 }
```

**Comment by kusumotonorio** [comment]
Sorry, I was mistaken to say that there was a bug in my cons-state pprint implementation.  It is same on scheme.
````
gosh> '((1 2).(2 3))
((1 2) 2 3)
````
Again, I would like to change the literal notation of cons-state.
When I tried `1 2 cons .` with  `factor-windows-x86-32-2019-10-16-13-25`:
```
IN: scratchpad USE: lists
IN: scratchpad 1 2 cons

--- Data stack:
L{ 1 ~more~ }
IN: scratchpad .
L{ 1 ~more~ }
```
The results of this print do not show that the cdr of this cons-state is 2. In that respect, the former is better.
```
T{ cons-state {car 1} {cdr 2} }
```
I actively use `cons-state`s where cdr are not another `cons-state` or `+nil+`. This new printing method and description syntax do not assume such a cons-state, and I will have to drop the use of the `lists` vocabulary. So I would like a printing method and description syntax that allows a dotted pair notation equivalent.

**Comment by mrjbq7** [comment]
There are other considerations. 

For example, infinite, or lazy lists:

```factor
IN: scratchpad { 1 2 3 4 5 } >list [ 2 > ] luntil
T{ lazy-until { cons L{ 1 ~more~ } } { quot [ 2 > ] } }
```

That's a lazy list object, that will yield elements when requested, and we don't want the prettyprint system to force it's evaluation.

We could have that be the second element in a ``cons-state``:

```factor
IN: scratchpad { 1 2 3 4 5 } >list [ 2 > ] luntil "first" swap cons .
L{ "first" ~more~ }
```

Some ideas, we could print all concrete ``cons-state`` elements in a list, stopping with ``~more~`` if we have too many items to print, or we hit a "lazy list" type of element.

I'm not a fan of dot-notation, because we have ``.`` which means something else, and because (as far as I understand) it always devolves to lists.  

Suggestions welcome on the prettyprint or list syntax, it's easy to change.   But we should be thoughtful about infinite and lazy cons.

**Comment by kusumotonorio** [comment]
> That's a lazy list object, that will yield elements when requested, and we don't want the prettyprint system to force it's evaluation.
> 
> We could have that be the second element in a cons-state:
> 
> IN: scratchpad { 1 2 3 4 5 } >list [ 2 > ] luntil "first" swap cons .
> L{ "first" \~more\~ }

This example rather makes me feel the need for something equivalent to dotted notation. In this example, the print does not give information about whether the value of cdr is a lazy list or something else.

The above example, by my definition, looks like this:
```
 IN: scratchpad { 1 2 3 4 5 } >list [ 2 > ] luntil "first" swap cons .
L{
    "first"
    ||
    T{ lazy-until { cons L{ 1 2 3 4 5 } } { quot [ 2 > ] } }
}
```
You may find this messy. You might want to:
```
L{ "first" ~and lazy items~ }
```

**Comment by mrjbq7** [comment]
Okay, I made an improvement based on your comment.

We now print up to the ``length-limit`` of items, or the first non-``cons-state`` encountered.  Right now, I'm leaving ``+nil+`` printing as the symbol instead of an empty ``L{ }``... thoughts?

f513a14e1c45c44f41b7e82bdbf2f646bf56fc86

```factor
IN: scratchpad L{ 1 2 3 4 5 } .
L{ 1 2 3 4 5 }

IN: scratchpad L{ } .
+nil+

IN: scratchpad L{ 1 2 3 4 5 } [ 2 > ] luntil "first" swap cons .
L{ "first" ~more~ }
```

**Comment by kusumotonorio** [comment]
This is what I have in mind.
```
MIXIN: lazy-list
INSTANCE: lazy-cons-state lazy-list
INSTANCE: lazy-until lazy-list
! and more

SYMBOL: ||  ! something that is a substitute for a dot

M: cons-state pprint*
    [
        <flow
        dup pprint-delims [
            pprint-word
            dup pprint-narrow? <inset
            [
                building get
                length-limit get
                '[ dup cons-state? _ length _ < and ]
                [ uncons swap , ] while
            ] { } make
            [ pprint* ] each
            dup lazy-list? [
                drop "~and lazy items~" text
            ] [ 
                dup list? [
                    drop "~more~" text
                ] [
                    || pprint* pprint* 
                ] if
            ] if
            block>
        ] dip pprint-word block>
    ] check-recursion ;
```

**Comment by kusumotonorio** [comment]
I make a partial correction.
-               dup list? [
-                    drop "~more~" text
+                dup list? [
+                   nil? [ "~more~" text ] unless

**Comment by kusumotonorio** [comment]
I think `L { }` is a better print representation of an empty list than `+nil+`.

**Comment by kusumotonorio** [comment]
If I change the method for `cons-state` to the method for `list`, the empty list will be printed as `L{ }`.
There seems to be nothing functionally missing.
If the standard implementation doesn't have this equivalent, I'll have to write my own list implementation and use it.
```
IN: scratchpad L{ 1 2 3 4 5 }
L{ 1 2 3 4 5 }

IN: scratchpad L{ }
L{ }

IN: scratchpad +nil+
L{ }

IN: scratchpad L{ 1 2 3 4 5 } [ 2 > ] luntil "first" swap cons
L{ "first" ~lazy list items~ }

IN: scratchpad { 1 2 3 } >list
L{ ~lazy list items~ }

IN: scratchpad 100 <iota> sequence>list
L{ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 ~more~ }

IN: scratchpad 1 2 cons
L{ 1 || 2 }

IN: scratchpad SYMBOL: others
IN: scratchpad 1 2 others cons cons
L{ 1 2 || others }
```

```
M: list pprint-delims drop \ L{ \ } ;

MIXIN: lazy-list
INSTANCE: lazy-cons-state lazy-list
INSTANCE: lazy-map lazy-list
INSTANCE: lazy-take lazy-list
INSTANCE: lazy-until lazy-list
INSTANCE: lazy-while lazy-list 
INSTANCE: lazy-filter lazy-list
INSTANCE: lazy-append lazy-list
INSTANCE: lazy-from-by lazy-list
INSTANCE: lazy-zip lazy-list
INSTANCE: lazy-concat lazy-list
INSTANCE: lazy-io lazy-list
INSTANCE: memoized-cons lazy-list
INSTANCE: sequence-cons lazy-list

SYMBOL: ||  ! something that is a substitute for a dot

M: list pprint*
    [
        <flow
        dup pprint-delims [
            pprint-word
            dup pprint-narrow? <inset
            [
                building get
                length-limit get
                '[ dup cons-state? _ length _ < and ]
                [ uncons swap , ] while
            ] { } make
            [ pprint* ] each
            dup lazy-list? [
                drop "~lazy list items~" text
            ] [ 
                dup list? [
                    nil? [ "~more~" text ] unless
                ] [
                    || pprint* pprint* 
                ] if
            ] if
            block>
        ] dip pprint-word block>
    ] check-recursion ;
```

**Comment by mrjbq7** [comment]
I’m a little conflicted because I like the pretty print functionality to have some element of homoiconicity, where the prettyprint representation is something like copy-pastable to the data representation. 

Maybe we shouldn’t make lazy list print like cons objects. The nil symbol is a weird special case. And your desire for the dot notation makes me think you should incubate a syntax that works for you and if it’s useful for more people or you find you really like it, we can absorb it into main Factor?

This syntax:

L{ 

Is a “list-like” object, but could be many different types in practice (mostly because of lists.lazy vocabulary, to be fair). 

Copy and pasting it makes either a concrete list or is not possible for cases of lazy iterators.

**Comment by kusumotonorio** [comment]
In fact, it doesn't really matter to me whether I can use a standard list for a library I've created. The list features I use are limited, so I can create an equivalent for myself. In fact, that was the initial implementation of logica.

What concerns me more is that if you print cdr in `~mode~`, the information about cdr is incomplete, making it impossible to reverse the print representation to the internal representation. And I think the equivalent of dot pair representation is necessary for a print format that can be converted back. Of course, to do so, the `L{` syntax must also be able to handle it.

The same is true for lists with lazy evaluation elements. I myself am reluctant to print the delayed list as `~lazy list items~` (or `~ more~`). This is because the information given is incomplete and the inverse is impossible.
