### ISSUE TITLE
vshuffle and prettyprinting int-4 has a resource leak

### ISSUE THREAD

**Issue by catb0t** [factor/factor#2055]
`help-lint-all` -> 

```
resource:basis/math/vectors/vectors-docs.factor: 448

Asset: T{ link f vshuffle }

Leaked resources: H{ { cache-assoc 2 } }
```

https://github.com/factor/factor/blob/master/basis/math/vectors/vectors-docs.factor#L457

```
USING: alien.c-types math.vectors math.vectors.simd prettyprint ;
[ int-4{ 69 42 911 13 } { 1 3 2 3 } vshuffle drop ] leaks.
```
(no leaks) 

```
USING: alien.c-types math.vectors math.vectors.simd prettyprint ;
[ int-4{ 69 42 911 13 } . ] leaks.
```
(no leaks) 

```
USING: alien.c-types math.vectors math.vectors.simd prettyprint ;
[ int-4{ 69 42 911 13 } { 1 3 2 3 } vshuffle . ] leaks.
```
gives 

| Disposable class        | Instances           |   |
| ------------- |:-------------:| -----:|
| layout     | 5 | [List instances] |

Each `layout` object is quite long but they all have their `disposed` field set to `t`. 

No idea how to debug the relevant methods `vshuffle-bytes` or `pprint-object`, but here's a pastebin of a leaked `layout` https://pastebin.com/8FvzPSpd

**Comment by mrjbq7** [comment]
The ``layout`` object is not really leaked, that's a Pango object and since you probably printed it into the UI listener, it's kept around because it's displayed in the user interface.

It happens on the Mac too, with ``line`` objects.

I'm not sure why the ``disposed`` slot is set to ``t``, though.  That might be a slight design flaw, since (like on the Mac), these are created, used to render text into a bitmap, and then the Pango/Core-Text/etc. objects are cleaned up by ``dispose``.  But the object is kept around for awhile since it has the cached rendering that the user interface needs to display it.

**Comment by catb0t** [comment]
This is fair, but why does help-lint-all report a cache-assoc leak when it's not being displayed in the UI?

**Comment by mrjbq7** [comment]
What platform do you see that ``cache-assoc`` thing on?  I can't seem to reproduce on Mac or Linux.

**Comment by catb0t** [comment]
It was on Linux, built from master. 

I could produce it from a fresh compile + build just five minutes ago, but I recompiled again (without any code change) and it's gone. Weird!
