### ISSUE TITLE
Travis-CI build issues

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2209]
On a recent pull request which only changes a text file, Travis CI still generates build errors. It seems to do so for quite some recent pull requests. What's wrong?

**Comment by mrjbq7** [comment]
We have a separate continuous build system that generates our nightly builds.

Travis isn't great for us because it can't run all of our tests.  They limit testing to 50 minutes and kill the Linux system if it's not done in that time-frame.  Our integration tests take longer than that.  We made some progress marking some tests as long running so that Travis doesn't run them, but haven't quite gotten there.

https://travis-ci.org/factor/factor/builds/605746460

The macOS tests don't seem to work right now for some reason with ``homebrew``:

```
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative': /usr/local/Homebrew/Library/Homebrew/global.rb:110: syntax error, unexpected keyword_rescue, expecting keyword_end (SyntaxError)

	from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'

The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions snappy > /dev/null || brew install snappy; fi" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by nomennescio** [comment]
I find it confusing that most of my pull requests get red crosses due to Travis errors, but actually it is Travis that is failing. Why not disable it for now then?

**Comment by timor** [comment]
If Travis always dies on the long-running tests, is there maybe a core test set which is known not to fail because of runtime which could be used instead?

**Comment by mrjbq7** [comment]
The tests don’t fail, they just take too long for our Travis allotment. We need to mark a few more tests as “long running” so they don’t run on Travis. And resolve the macOS configuration (also a Travis issue).

I agree that it’s frustrating having Travis run and error for wrong reasons. Should try and fix soon.
