### ISSUE TITLE
Errors in "compiler" test

### ISSUE THREAD

**Issue by kusumotonorio** [factor/factor#2234]
`"compiler" test` seems to detect errors 3 times, but they disappear. 

I took screenshots while they were displayed. Don't we have to worry about them?

![error1](https://user-images.githubusercontent.com/47816570/72673314-e9875300-3aab-11ea-8e01-db696b891e4b.png)
![error2](https://user-images.githubusercontent.com/47816570/72673317-ec824380-3aab-11ea-9e75-dc6d968ebfcf.png)
![error3](https://user-images.githubusercontent.com/47816570/72673319-f0ae6100-3aab-11ea-8074-dea5c3e34a07.png)

**Comment by catb0t** [comment]
It's hard to find, but somewhere there are GitHub issue comments about how (probably these same tests) are intentionally failing this way, by design and/or because the failure cause is fixed before the tests finish -- essentially, they are not bugs.

I can't produce a citation link but I'm quite sure that's the answer the maintainers will give.

**Comment by kusumotonorio** [comment]
I see. Thanks, @catb0t !
