### ISSUE TITLE
Arrow keys to browse code previously entered in listener

### ISSUE THREAD

**Issue by luc-j-bourhis** [factor/factor#2240]
Basically like shells behave. Pressing up arrow would bring the last line of code, then the next-to-last, etc and pressing down arrow would go in the reverse direction.

**Comment by AlexIljin** [comment]
There are the `C-p`, `C-n` and `C-r` to browse the history.
The problem with the simple arrow key is that they must only work in a subset of cases, because you can enter a multiline statement using `S-Enter`. If you press `Up` to recall such a statement, what should pressing `Down` next do? Should it move caret to the second line, or should it restore the next statement from the history?

**Comment by mrjbq7** [comment]
If you want that in the command-line, you can do either:

```
$ rlwrap ./factor
```

or

```
$ ./factor -run=readline-listener
```

**Comment by erg** [comment]
Please reopen if there's anything actionable here. Thanks!
