### ISSUE TITLE
Compilation fails with Windows x86.64

### ISSUE THREAD

**Issue by itmuckel** [factor/factor#2316]
I downloaded the latest Windows x86.64, compiled a program and ran into this issue:

I get 
"Process exited with error code 1

Launch descriptor:"
```
T{ process
    { command
        {
            "\\\\?\\C:\\factor\\factor-lsp\\factor-lsp.exe"
            "-pic=0"
            "-i=C:\\Users\\Admin\\AppData\\Local/factorcode.org\\Factor/staging..."
            "-vocab-manifest-out=C:\\Users\\Admin\\AppData\\Local\\Temp/factorc..."
            "-deploy-vocab=factor-lsp"
            "-deploy-config=C:\\Users\\Admin\\AppData\\Local\\Temp/factorcode.o..."
            "-output-image=C:\\Users\\Admin\\AppData\\Local\\Temp/factorcode.or..."
            "-resource-path=C:\\factor\\"
            "-run=tools.deploy.shaker"
        }
    }
    { environment H{ } }
    { environment-mode +append-environment+ }
    { stdin +closed+ }
    { stdout
        T{ win32-file { disposed t } { handle ALIEN: 28cc } }
    }
    { stderr +stdout+ }
    { priority +low-priority+ }
    { group +same-group+ }
    { status 1 }
    { pipe
        T{ pipe
            { in
                T{ win32-file
                    { disposed t }
                    { handle ALIEN: 27a4 }
                }
            }
            { out
                T{ win32-file
                    { disposed t }
                    { handle ALIEN: 28cc }
                }
            }
        }
    }
}
```

This is the offending repo: https://github.com/itmuckel/factor-lsp

**Comment by mrjbq7** [comment]
It deploys fine on my macOS that I just tried.

I suspect it has to do with out-of-date staging images which are not cleaned up when upgrading to newer Factor versions (currently).

Try running ``delete-staging-images`` and then try deploying again?

**Comment by itmuckel** [comment]
Wow! Perfect, that did it!
Indeed I had 0.98 stable before and then switched to the latest nightly version. Can you expand on staing images? What are those and why do they lead to compilation errors? 🤔

**Comment by mrjbq7** [comment]
Think of them as cached compilation to speed up deploy processes from starting with a "mostly everything in the standard library" you would need.  Unfortunately, they aren't versioned, so there is no machinery to detect out-of-date images.   This really only impacts version upgrades, or if you track nightly builds you might run into that issue slightly more often.

When you ``delete-staging-images``, the next time you deploy it will recreate those image files against your current version of Factor, and then use those for subsequent deploys.

P.S., you might consider re-arranging your code so that it has an outer project directory that can be added to ``.factor-roots`` and inner vocabulary directories that can be imported. It looks like you intend to put that ``git clone`` somewhere that's already a root, which is fine, except not as easy to include for other people.  Didn't actually look at what it does, but if there's anything we can help with, or any improvements we can make to assist you, or anything you want to upstream pull request, let us know!
