### ISSUE TITLE
Remove (or upgrade?) a copy of jQuery from factor

### ISSUE THREAD

**Issue by hiljusti** [factor/factor#2403]
There's an old version of jQuery (1.3.2) packaged with a JavaScript parsing benchmark script here: https://github.com/factor/factor/blob/master/extra/benchmark/javascript/javascript.factor

It's a benchmark for this javascript parser: https://docs.factorcode.org/content/vocab-peg.javascript.html

Versions of jQuery (prior to 3.5) have a fairly recent XSS vulnerability: https://www.infoq.com/news/2020/04/jquery-35-xss-vulnerability-fix/

It looks like the file is not used in any way that would expose the XSS bug, but for what it's worth it gets flagged as sketchy by some kinds of vulnerability scans my current project uses. Maybe other users will get that noise too?

Some other thoughts:

- Having a parser for JS at all sounds cool, though does the world really, *really* needs another? (Well, if it's written in Factor... maybe!)
- It looks like it's been about 3 years since the project's been touched: https://github.com/factor/factor/tree/master/extra/peg/javascript - most notably it looks like it's only capable of parsing pre-ES6 syntax, and missing "fat arrow" lambda syntax. (It will also miss null-coalescing operators `??` soon too)

It might be best to abandon the whole JavaScript parser for now, benchmarks and all. It's testing some influential, but questionable code. Also it wouldn't handle modern JavaScript. The language moves a little too fast to lack an active maintainer. (A languages like C may be a better candidate? It does continue to get updates but changes *syntax* far less frequently)

**Comment by mrjbq7** [comment]
Upgraded to 3.5.1 in 6e7df6b695f6edefe41bf058d4908c44b492c0c0.

As it turns out, I was looking at ``benchmark.javascript`` recently.  Our EBNF parsers could silent not parse the entire input and were changed to assert full parse by default in d9584c602d73d9d51a43d6471ba9d83763ebaac4.

When that change was made, it became obvious that our benchmark wasn't parsing the full input, mostly due to some tokenizing confusion between regex literals and division operators maybe?

I pretty much love all code, I'm not sure what a Javascript parser would be useful for in Factor, aside from being a use case and performance test for our PEG parsing framework.  I can't imagine it would be too hard to fix this division bug or add support for more modern Javascript syntax... but you're right, it all depends on having an interested party to work on it.

**Comment by hiljusti** [comment]
Wow, that was fast! Does it still parse?

Also, I don't mean anything *against* JavaScript. I love it too, although I don't love some of the abuse the language gets. Also the language's syntax itself feels like a good fit for parser benchmarking, it's lisp-ish and c-ish all in one package, and also I don't see the language going anywhere in the next few years.

Anyway, the change saves me from noise! Sorry for getting late-night rambly about other things.

**Comment by mrjbq7** [comment]
I love late night rambly!

Thanks for the report!
