### ISSUE TITLE
oauth1: invalid request/memory violation

### ISSUE THREAD

**Issue by gifti258** [factor/factor#2487]
Small requests work fine, bigger requests return a HTTP 400 error, and even bigger requests try to access an invalid memory location (making (shutdown) on the secure socket a no-op makes this a broken socket, so I think the server just drops the connection).

edit: https://github.com/factor/factor/issues/2487#issuecomment-998175785 is the current problem -@erg

**Comment by mrjbq7** [comment]
Do you have an example of requests that break?  Or perhaps can suggest some examples to try?

**Comment by mrjbq7** [comment]
What platform are you on?

I get a 200 OK on macOS 64-bit (running the above example, with the commented out line).

**Comment by gifti258** [comment]
Interesting, thank you. My platform is Linux 64-bit.

**Comment by mrjbq7** [comment]
I can reproduce the problem on Linux x64, although I'm not sure what the root cause is.  Thanks for the report!  Hopefully we can get it resolved soon.

**Comment by bpollack** [comment]
Which Linux distro are you on, @mrjbq7? I can take a look. We're using OpenSSL on all nix platforms, including macOS, so it "shouldn't" be platform-specific, but we may have a version incompatibility, since I know macOS' OpenSSL is out-of-date.

**Comment by mrjbq7** [comment]
Tested on Ubuntu 20.04.

**Comment by mrjbq7** [comment]
@bpollack did you ever look at this?

**Comment by mrjbq7** [comment]
It's interesting that the "crash" case somehow is associated with an ``Authorization`` header that's 304,525 bytes long.

This is an aside, but a lot of web servers have a max header size of 8k or 16k.

Trying this same request against factorcode.org results in a "400 Request Header Or Cookie Too Large" response.

So, perhaps related to something the server is sending back?  Need to investigate further.

**Comment by erg** [comment]
The server is closing the connection due to the large header and we attempt to ``shutdown`` the socket afterwards. It doesn't need to be shut down, and a lot of the error handling was broken/duplicated/awkward.

Thanks for reporting the bug and reducing the test case!

**Comment by gifti258** [comment]
Oh, wow, thanks a ton!

**Comment by erg** [comment]
No problem!

Here's the errors now:

```
! 100,000 cut error message:
error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry

It calls ``drain`` to empty the socket descriptor but fails due to server disconnecting. We could maybe do better here?


10000 cut drop error message:
HTTP request failed:

T{ response
    { version "1.1" }
    { code 400 }
    { message "Bad Request" }
    { header H{ { "connection" "close" } } }
    { cookies { } }
    { content-encoding utf8 }
    { body "" }
}

100 cut ! error message:

H{
    {
        "error"
        H{
            {
                "info"
                "The authorization headers in your request are not valid: Invalid consumer"
            }
            { "code" "mwoauth-invalid-authorization" }
            {
                "docref"
                "See https://de.wikipedia.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/&gt; for notice of API deprecations and breaking changes."
            }
        }
    }
    { "servedby" "mw1428" }
}
```

**Comment by gifti258** [comment]
I can confirm the SSL error. Maybe we should keep the issue open then?

**Comment by erg** [comment]
I think the SSL error is fine because we throw it from Factor when the write fails (after the server closes our socket) as expected.

Maybe we could include the name of the failed SSL API to improve it?

**Comment by gifti258** [comment]
Is this an operation that should fail (if provided with valid tokens)? It works in other languages. Do they not send these large headers? So, I think there still is a bug somewhere? Is it possible to make it work in Factor?

**Comment by erg** [comment]
Oh, I didn't know it is supposed to work instead of just not crash.

So the server should accept this and return something good? We are not there yet :p

**Comment by mrjbq7** [comment]
I don’t think this should work. 

Http headers almost always can’t be this large. 

Also, @erg the behavior of ZERO_RETURN changed in ssl-accept? Intentional?

**Comment by erg** [comment]
@gifti258 Do you have working python/javascript that succeeds with this large header?

@mrjbq7 If I throw there, the first time it throws ``error:00000000:lib(0):func(0):reason(0)`` and the second time it hangs. Now ignoring it throws a messed up write error on macOS in the largest case, which is expected since the server kills it, and in the linux case it actually throws the same error as the ``10,000 cut`` case, which is a ``response`` with ``"Bad Request"``.

However, according to https://stackoverflow.com/questions/50223224/ssl-read-returns-ssl-error-zero-return-but-err-get-error-is-0 it's a server disconnect, so I'm now setting ``t >>terminated`` and ``f >>connected``. It works on Linux, going to see if it is better on macOS.

**Comment by erg** [comment]
It's no better/worse after 14c57cb, still throwing ``"error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry"`` on macOS.

There's still a bug where I believe ``SSL_write`` returns ``-1`` and that gets set to the buffer ``pos`` slot and it tries to write ``65537`` bytes because of ``buffer-capacity`` arithmetic. Maybe buffers themselves should not let the ``pos`` go out of bounds.

**Comment by gifti258** [comment]
@erg I do not have working examples in your requested languages as I'm not comfortable in them. I would only have a Tcl library and am too lazy to write an example from it.

However, I have a patch, sort of. With this, it now gives a reasonable result (it would still need proper oauth and CSRF tokens to work, but that does not matter now). I do not know if this is the right place in the code, or if `build-auth-string` is the proper place? Or somewhere or something else entirely? Like properly separating OAuth and HTTP parameters from the start.

**Comment by erg** [comment]
If you post the patch I will try to improve the libraries.

**Comment by gifti258** [comment]
It's this one: 3c9837c, right above my comment.

**Comment by erg** [comment]
Does that authenticates with valid oauth tokens? It looks right.

**Comment by gifti258** [comment]
It does.

**Comment by erg** [comment]
Ok! The only issue left is that your original test case with the long headers (with 11f82078dcf2a389b7261f4f2683207128640d57 reverted) will sometimes set the ``buffer`` ``pos`` to ``-1`` which attempts to write 65537 bytes. This obviously fails but doesn't crash. We could probably fix something here, like if ``do-ssl-write`` fails then retry it instead of trusting that it wrote -1 bytes.

**Comment by erg** [comment]
Closing this issue, tracking in #2508
