### ISSUE TITLE
"1 2 3" infer should error

### ISSUE THREAD

**Issue by erg** [factor/factor#2643]
```factor
"1 2 3" infer .
( -- x x x x x )
```

**Comment by twopir** [comment]
```factor
IN: scratchpad "abc" infer .
( -- x x x )
IN: scratchpad { 1 2 3 } infer .
( -- x x x )
```

looks like sequences, in general, are inferred as though their individual elements all become stack items. should it just be prevented on strings?

**Comment by mrjbq7** [comment]
I don’t think it makes sense to infer anything that’s not a word or callable. We could make it throw I guess.

**Comment by erg** [comment]
Yeah. I was trying to infer a quotation and noticed it didn't fail for a string like I expected.

**Comment by twopir** [comment]
Making it throw an error breaks bootstrap, alas; it seems like something in the class/throwing infrastructure isn't set up when trying to throw.

Trying this instead:

```factor
: infer ( quot -- effect )
    dup callable? not
    [ drop ( -- x ) ]
    [ [ infer-quot-here ] with-infer drop ] if ;
```

This infers all things that aren't callable to be self-evaluating, instead of inferring a sequence as something which stacks all its elements.

**Comment by mrjbq7** [comment]
Have to check words too for e.g., ``\ + infer``

**Comment by twopir** [comment]
oh, good catch.

**Comment by twopir** [comment]
turns out really only callables should be inferred; words are handled by `M: word stack-effect`.

The failing windows test in PR #2649 is bootstrap failure due to missing an image; not caused by this.
