### ISSUE TITLE
GUI scaling is off until window resize

### ISSUE THREAD

**Issue by ssfrr** [factor/factor#2799]
I just installed factor v0.98 via homebrew on mac. When I run Factor.app the listener window pops up but it looks blank. If I resize the window though, everything shows up. This happens with every new window that opens up, I think the scaling is off. If I click "All tips of the day" I get a window like this:

<img width="300" alt="image" src="https://github.com/factor/factor/assets/734386/95e1e305-f0b9-41fe-9573-33007bb4cb41">

then as soon as I start resizing the window it snaps to the correct scale:

<img width="300" alt="image" src="https://github.com/factor/factor/assets/734386/8222c471-dd1d-434f-81ef-7dddb28ceab4">

**Comment by mrjbq7** [comment]
Fixed in current master and soon to be released 0.99!On Jul 13, 2023, at 7:39 PM, Spencer Russell ***@***.***> wrote:﻿
I just installed factor v0.98 via homebrew on mac. When I run Factor.app the listener window pops up but it looks blank. If I resize the window though, everything shows up. This happens with every new window that opens up, I think the scaling is off. If I click "All tips of the day" I get a window like this:

then as soon as I start resizing the window it snaps to the correct scale:

**Comment by mrjbq7** [comment]
I recommend using a nightly build from factorcode.orgOn Jul 13, 2023, at 7:39 PM, Spencer Russell ***@***.***> wrote:﻿
I just installed factor v0.98 via homebrew on mac. When I run Factor.app the listener window pops up but it looks blank. If I resize the window though, everything shows up. This happens with every new window that opens up, I think the scaling is off. If I click "All tips of the day" I get a window like this:

then as soon as I start resizing the window it snaps to the correct scale:

**Comment by ssfrr** [comment]
oh great, thanks! confirmed it's fixed with the nightly.

**Comment by mrjbq7** [comment]
And the nightly will be 99% of the 0.99 experience. We are waiting for a
certificate renewal to sign windows binaries and then planning a release.

Many bugs fixed, many features added since 0.98.
