### ISSUE TITLE
regarding representation of json objects in factor

### ISSUE THREAD

**Issue by razetime** [factor/factor#2800]
Currently `json>` returns a hashtable when it detects a JSON object in the given string.
It would be semantically more correct to return a list of pairs when given an object instead.

This issue is also open for discussion on other ways to fix this minor issue (`read-json-object-as` seems a bit clunky), and on what will be affected by such a change.

**Comment by mrjbq7** [comment]
Can you give an example ?On Jul 19, 2023, at 7:43 AM, Raghu R ***@***.***> wrote:﻿
Currently json> returns a hashtable when it detects a JSON object in the given string.
It would be semantically more correct to return a list of pairs when given an object instead.
This issue is also open for discussion on other ways to fix this minor issue (read-json-object-as seems a bit clunky), and on what will be affected by such a change.

**Comment by razetime** [comment]
Here `json>` provides a hashtable, which does not preserve the original order of elements in the object. this is sometimes significant for json payloads. A user asked for help with this problem in the chatroom as well.
```
IN: scratchpad "{\"a\": 5, \"b\": 6, \"aa\": 17}" json>

--- Data stack:
H{ { "aa" 17 } { "a" 5 } { "b" 6 } }
```

**Comment by razetime** [comment]
An `LH{` seems good, preserving characteristics of both. I assume vocabularies using `json` would need to use a different protocol, if we change to `linked-assoc`?

**Comment by mrjbq7** [comment]
Users of json wouldn’t need to care, it would be transparent for them
except for it being order preserving.

**Comment by razetime** [comment]
`json>` now returns linked-assocs in 6a83f9e.
