### ISSUE TITLE
move rosetta-code out of main repo?

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#2842]
The authoritative solutions for Rosetta Code are on their website:

https://rosettacode.org/wiki/Category:Factor

Perhaps we should delete / move the ``extra/rosetta-code`` out of the main repo?

There are quite a few solutions on the Rosetta Code wiki that aren't in this repo... so the other alternative is to add the other solutions and track them here also... but that seems like unnecessary work.

**Comment by razetime** [comment]
yeah, we can leave them in unmaintained, makes sense to do so. rosetta is backed up regularly so a mirror here is redundant.

**Comment by mrjbq7** [comment]
do you think it makes sense to have a ``factor-rosetta-code`` repo?

or just put in unmaintained

**Comment by alex-ilin** [comment]
I like having all stuff in `extra`: it's good for discoverability.
I would only put stuff in unmaintained if it fails compilation, on a per-vocab basis.

**Comment by mrjbq7** [comment]
in this case its kind of not the authority, nor is it kept updated, so its both good example code, and unlikely to be added to much

**Comment by erg** [comment]
Rosetta code in factor doesn't make sense to me. We could have a separate repo and try to sync it when the code changes on Rosetta code

**Comment by alex-ilin** [comment]
I would probably never have learned about Rosetta if it weren't in Factor.

**Comment by jonenst** [comment]
Maybe write a tool to pull/run/modify the code for a given task ?
And then manually or automatically resolve all diffs between the repo and the website so that we don't lose anything and store the result on the website and delete from the repo?

I guess the only downside is that code from the factor repo is more trusted. Or we could keep the authoritative code in the repo for trust and write a periodic tool to sync to/from the website after code is approved as safe. But that's more work?

**Comment by mshure** [comment]
I also like having all stuff in 'extra' for better discoverability. I found Rosetta code examples very helpful while learning about Factor.

**Comment by razetime** [comment]
it's simpler to keep it in unmaintained, since it will remain unmaintained, not updated.

**Comment by mrjbq7** [comment]
Moved to factor-unmaintained in 1976856a810e63e294e7da8ddfb3d4b88e778ce7
