### ISSUE TITLE
`append-relative-path` incorrectly uses fixed and incorrect path separator on Windows

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2966]
```
USING: kernel sequences ;
IN: io.pathnames
: append-relative-path ( path1 path2 -- path )
    [ trim-tail-separators ] [ trim-head-separators ] bi*
    "/" glue ;
```

~~This leads to bugs in e.g. `run-mason` because of unexpected path names~~

**Comment by mrjbq7** [comment]
Can you give an example?

Normally factor / paths work on windows because they are normalized before
calling C

**Comment by nomennescio** [comment]
Yes, I got a path with mixed slashes which failed in the Walker. I clicked it away so I first need to try to reproduce it. But the fix is very simple; replace `"/"` with `path-separator`. I've submitted it as fix, if you think it's incorrect, please revert.

**Comment by mrjbq7** [comment]
Fix is fine, just wondering if we missed a C api call where we don’t
normalize-path first.

**Comment by nomennescio** [comment]
Example code is:
on stack:
`"C:\\factor\\LICENSE.txt"`
call `canonicalize-path`, result is incorrect:
`"C:/factor\\LICENSE.txt"`

I'm not sure if this will trigger an issue with the C API call, as indeed, usually mixed path separators are usually fine. However, in this case it violates the intention of `canonicalize-path`.

I will further check if the C API gave the issue further on.

**Comment by mrjbq7** [comment]
normalize-path is more typically used. canonicalize-path is some UNC path
support thing that maybe needs better integration. Dunno why slashes change

**Comment by nomennescio** [comment]
Slashes changes because of `append-relative-path`, but not anymore.

I can't reproduce the error right now, so the C API is probably fine.

**Comment by nomennescio** [comment]
As an aside; I wouldn't mind start using '/' for all Windows paths, which is what I personally do in my code. I can't remember if there are special cases which really need `\\`. It makes path strings a lot easier, and it would give more clear code in Factor too.

**Comment by mrjbq7** [comment]
Forward slash should work fine on windows, it’s normalized before calling Windows API. That’s why I’m confused where the bug is. Your change makes it visually more consistent but should maybe mask the bug not fix it?On Apr 28, 2024, at 8:12 AM, nomennescio ***@***.***> wrote:﻿
As an aside; I wouldn't mind start using / for all Windows paths, which is what I personally do in my code. I can't remember if there are special cases which really need \\. It makes path strings a lot easier, and it would give more clear code in Factor too.

**Comment by nomennescio** [comment]
I stepped through the walker, and the error I encountered was not related to the path, so no worries. Nevertheless the bug in `canonicalize-path` was real given its contract.

As for the `/` vs '\\`; the only thing I see mentioned where `\\` is needed is with escaped (long) UNC paths and as argument to external programs that process paths and expect it.

**Comment by mrjbq7** [comment]
We could look at pathlib in Python. They do a decent job of both cross platform and platform specific. On Apr 29, 2024, at 10:10 AM, Doug Coleman ***@***.***> wrote:﻿
canonicalize-path* uses path-separator join near the end. i kind of want to revert this and fix it so it uses / instead of the platform path separator. basically i want to always have / in path names because it's more cross-platform. we might even have to fix c:/ as well.
also we shouldn't have had "/" as a literal anywhere, we should have a CONSTANT: cross-platform-path-separator "/" maybe

**Comment by erg** [comment]
This is the wrong fix. Can you give me a test case of what is breaking? We have been running mason with this code on Windows since 2008.
