### ISSUE TITLE
Listener input is lost if typed before prompt displays

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#375]
If you load a vocab that takes a little while, and type something that you want to be run in the next prompt, it will get lost.

Mac OS X 10.7.2

**Comment by bjourne** [comment]
Funny. Seem to depend on how you load the vocabs. `USE: furnace` <- input is lost. `"furnace" use-vocab` <- input is preserved!

**Comment by mrjbq7** [comment]
It seems to show the previous input on (successful) restarts:

```factor
IN: scratchpad USING: readline readline.ffi ;
Loading resource:extra/readline/readline.factor
Loading resource:extra/readline/ffi/ffi.factor
Loading resource:extra/readline/readline-docs.factor

IN: scratchpad \ readline see

IN: scratchpad Command: continue-restart
USING: alien.strings destructors io.encodings.utf8 kernel libc
readline.ffi sequences ;
IN: readline
: readline ( prompt -- str )
    [
        readline [
            |free utf8 alien>string
            [ [ add_history ] unless-empty ] keep
        ] [ f ] if*
    ] with-destructors ;

IN: scratchpad \ readline see
```

**Comment by bjourne** [comment]
Yes... Hm that's tricky. I didn't think of that. It might be tricky to differentiate between a lexer-error which is solved by choosing one of the restarts and one in which you choose abort.

**Comment by mrjbq7** [comment]
Maybe we revert the change and make a pull request that we can try out and play with? I dunno. @erg?

**Comment by bjourne** [comment]
Anyway, the original problem with typing `USE: somevocab` in the listener is that because `USE:` is a syntax word, so loading of `somevocab` occurs while that expression is being parsed. And because parsing happened before the line was finished, when you typed more characters they went into the current line and not the next one.

**Comment by mrjbq7** [comment]
The new parser will be able to fix that with a lexer step before a parse/compile step which will allow "is it valid syntax" before the USE is run.

**Comment by bjourne** [comment]
See if you like the latest commit? Now it should only show the last input if the error was aborted and not restarted. If not, just revert!

**Comment by mrjbq7** [comment]
@bjourne okay so I love being able to type and have input preserved, but I don't like having invalid statements in the history...

Try doing some bad inputs a couple times and doing Ctrl-P/N they're in the history.

Also UP/DOWN is still weird for me since I often try to use multiple lines to format stuff like this and use up/down to navigate the lines:

```
"/path/to/stuff" [
    do some stuff
    do more stuff
    finish up
] with-directory
```

**Comment by erg** [comment]
The up/down arrows should only navigate in the current input gadget imo, not scroll through the input history. I tried it the new way and I end up scrolling through the history a bunch when I don't mean to.

**Comment by bjourne** [comment]
So I reverted the commit that added the UP & DOWN keybindings. @mrjbq7 Why does it matter if invalid commands are stored in the history? If you type an invalid command in other command prompts, like bash or Python's shell, it is saved. It's also what happens if you run factor with `-run=readline-listener`. 

I guess you could remove the last history item at the point where it checks if the last command was a lexer-error that was aborted. But you can't easily erase what has been written to the output buffer so it and the history list would become out of sync.

**Comment by mrjbq7** [comment]
Well it doesn't matter tremendously but i like having only "valid" Factor in the history (old behavior). @erg?

**Comment by mrjbq7** [comment]
This is weird.

```
IN: scratchpad USE: gopher-ui
IN: scratchpad open-gopher-window
```

It throws a stack underflow but somehow still opens the window???

**Comment by mrjbq7** [comment]
Nevermind, I'm an idiot (and sleep deprived).  It calls ``open-status-window`` before ``show-gopher``.

**Comment by catb0t** [comment]
I think this is closed, and all of its tangents are as well, at least, on Windows and Linux (don't know about Mac, don't know why it would be different).

**Comment by bjourne** [comment]
I think so too, please reopen if it isn't.
