### ISSUE TITLE
Help lint misses out on errors in pages

### ISSUE THREAD

**Issue by jckarter** [factor/factor#409]
As of 1753990cdb7cc5c8128e4cf0570ff35089ed3229 if you do `"ui-layouts" help` there's an error in the middle of the page. We should fix that, but we should also fix help-lint so it doesn't let that slide.

**Comment by razetime** [comment]
Copying the `ui` docs from the given commit gives the following help-lint error:
```
T{ help-lint-error
    { error
        T{ simple-lint-error
            { message
                "$values don't match stack effect; expected { \"quot\" \"world/f\" }, got { \"quot\" \"world\" }"
            }
        }
    }
    { asset T{ link { name find-window } } }
    { path "resource:basis/ui/ui-docs.factor" }
    { line# 43 }
}
```

**Comment by razetime** [comment]
copying ui docs from the given commit and checking the actual page linked here, it doesn't load on latest commit (produces an error on an undefined word) and it's not obvious how to reproduce the error in the middle of the page either. help-lint does notify on mid-page errors now, so this should likely be closed due to non-reproducibility.

**Comment by mrjbq7** [comment]
It's possible that there is some syntax thing we don't check, if we ever notice it again let's open another issue.
